name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
      - run: pip install mkdocs==1.6.1 mkdocs-material==9.5.49
      - run: mkdocs gh-deploy --force
